### ISSUE TITLE
Doesn't work in Blender 3.0

### ISSUE THREAD

**Issue by Alumx** [Radivarig/UvSquares#43]
I had this error when tried to run UV square tool
```
location: <unknown location>:-1
Error: Python: Traceback (most recent call last):
  File "C:\Users\Vas_v13\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\UvSquares-master\uv_squares.py", line 871, in execute
    main(context, self)
  File "C:\Users\Vas_v13\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\UvSquares-master\uv_squares.py", line 52, in main
    main1(obj, context, operator, square, snapToClosest)
  File "C:\Users\Vas_v13\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\UvSquares-master\uv_squares.py", line 144, in main1
    main2(targetFace, island)
  File "C:\Users\Vas_v13\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\UvSquares-master\uv_squares.py", line 133, in main2
    else: FollowActiveUV(operator, me, targetFace, faces)
  File "C:\Users\Vas_v13\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\UvSquares-master\uv_squares.py", line 480, in FollowActiveUV
    bmesh.update_edit_mesh(me, False)
TypeError: update_edit_mesh() takes at most 1 positional argument (2 given)
```

**Comment by Maaslandmods** [comment]
This is what I came along when using 'Snap with Equal Distance'. Selecting one face of an island. 
`Python: Traceback (most recent call last):
  File "C:\Users\maasl\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\uv_squares.py", line 927, in execute
    main(context, self)
  File "C:\Users\maasl\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\uv_squares.py", line 52, in main
    main1(obj, context, operator, square, snapToClosest)
  File "C:\Users\maasl\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\uv_squares.py", line 144, in main1
    main2(targetFace, island)
  File "C:\Users\maasl\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\uv_squares.py", line 133, in main2
    else: FollowActiveUV(operator, me, targetFace, faces)
  File "C:\Users\maasl\AppData\Roaming\Blender Foundation\Blender\3.0\scripts\addons\uv_squares.py", line 480, in FollowActiveUV
    bmesh.update_edit_mesh(me, False)
TypeError: update_edit_mesh() takes at most 1 positional argument (2 given)

location: <unknown location>:-1
`
