### ISSUE TITLE
UV Squares not working on Blender 3.2

### ISSUE THREAD

**Issue by 3dcinetv** [Radivarig/UvSquares#50]
Hello. UV Squares in Blender 3.2 is not working.
I get this error when I applied "to grid by shape". 
The addon doesn't work, and throws this error:

Python: Traceback (most recent call last):
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\UvSquares-master\uv_squares.py", line 857, in execute
    main(context, self, True)
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\UvSquares-master\uv_squares.py", line 52, in main
    main1(obj, context, operator, square, snapToClosest)
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\UvSquares-master\uv_squares.py", line 144, in main1
    main2(targetFace, island)
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\UvSquares-master\uv_squares.py", line 132, in main2
    if square: FollowActiveUV(operator, me, targetFace, faces, 'EVEN')
  File "C:\Users\3DCompositor\AppData\Roaming\Blender Foundation\Blender\3.2\scripts\addons\UvSquares-master\uv_squares.py", line 480, in FollowActiveUV
    bmesh.update_edit_mesh(me, False)
TypeError: update_edit_mesh() takes at most 1 positional argument (2 given)

**Comment by Radivarig** [comment]
Update to 1.14.1 and restart Blender.
