### ISSUE TITLE
Issue with Blender 4

### ISSUE THREAD

**Issue by olliebarbs** [Radivarig/UvSquares#59]
I'm having an issue with the addon and blender 4.0.1. I can install the addon without issue but when I try to use it I receive this traceback.

`Python: Traceback (most recent call last):
  File "C:\Users\Ollie\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\UvSquares-master\uv_squares.py", line 871, in execute
    main(context, self)
  File "C:\Users\Ollie\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\UvSquares-master\uv_squares.py", line 52, in main
    main1(obj, context, operator, square, snapToClosest)
  File "C:\Users\Ollie\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\UvSquares-master\uv_squares.py", line 144, in main1
    main2(targetFace, island)
  File "C:\Users\Ollie\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\UvSquares-master\uv_squares.py", line 133, in main2
    else: FollowActiveUV(operator, me, targetFace, faces)
  File "C:\Users\Ollie\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\UvSquares-master\uv_squares.py", line 480, in FollowActiveUV
    bmesh.update_edit_mesh(me, loop_triangles=False)
TypeError: update_edit_mesh() takes at most 1 positional argument (2 given)
`

I've tested and all works in 3.6

Interestingly, removing the `loop_triangles=False` from line 480 seems to make it work, though I'm sure this breaks functionality elsewhere.

**Comment by Radivarig** [comment]
Can you attach a minimal repro .blend file with steps please? I cannot reproduce this on 4.0.1, so it might be specific to the object you're unwrapping.
